### ISSUE TITLE
1.18.2 support or CraftTweaker script?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [LiteraDev/ImprovedNetherStar-DataPack#1]

**Comment by LiteraDev** [comment]
The current release (v1.1.2) should be working on 1.18.2 as well. The only items that cannot be crafted in this version are the Sculk Catalyst and Reinforced Deepslate added on 1.19 snapshots.

This is a datapack made to work independently and wasn't made to work with CraftTweaker, but they might work if put together in the same world.

**Comment by vadim-a-yegorov** [comment]
> The current release (v1.1.2) should be working on 1.18.2 as well. The only items that cannot be crafted in this version are the Sculk Catalyst and Reinforced Deepslate added on 1.19 snapshots.
> 
> This is a datapack made to work independently and wasn't made to work with CraftTweaker, but they might work if put together in the same world.

No I meant instead of installing a datapack you can provide CraftTweaker script to add your recipes. But if it's working on 1.18.2 then nevermind. Thanks I'll try.
